# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjNmNWUzNjFkYTQ4Yjc0YzI1NmRmMzY4OTU5YWQxZjdkMjRhNDRmY2JmN2U5Yjc1Yjk0NWEyMWE3ZmM1N2VkZjYyMmMyOGU5ZTM3Nzg4Nzc4Yzg0MzI2OGJlODI5OGRlMDVlMzBkYmM5OWY2YzdhMmFhNGM2NDYyZmQwYjA5ZTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
