# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTg2ODhhMTM3YzA2N2Y0MTVmYjE2YjFmNzgzMjNjNDYyNzI3MDFhMWFlZjc0NmUwMDQyNmM3ODQ0Y2IyOWZjNTRkNDZjMDYzZjYyMzk3MzVlYWY0YjU0Yzg0Yzk2MjdlNWNhNTkyYWZmODFhZWJmZTQ0NjA2M2Q1ZTQ2NzA3NDY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
