insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9151, null, null, 'argileuse', null, null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9152, null, null, 'calcaire', null, null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9153, null, null, 'humifere', null, null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9154, null, null, 'sableuse', null, null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9155, null, null, null, 'tresPauvre', null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9156, null, null, null, 'pauvre', null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9157, null, null, null, 'normale', null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9158, null, null, null, 'riche', null);
insert into public.sol (id, ph_min, ph_max, type, richesse, plante_id) values (9159, null, null, null, 'tresRiche', null);
