insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9651, 'Inconnu', '', 5, 9351, 9376);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9652, 'Inconnu', 'L’aneth protège les carottes et aide à la levée', 5, 9351, 9352);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9653, 'Inconnu', '', 5, 9351, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9654, 'Inconnu', '', 5, 9351, 9378);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9655, 'Inconnu', '', 5, 9351, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9656, 'Inconnu', '', 5, 9351, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9657, 'Inconnu', '', 5, 9351, 9379);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9658, 'Inconnu', '', 5, 9351, 9354);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9659, 'Inconnu', 'L''oignon repousse la mouche de la carotte', 5, 9351, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9660, 'Inconnu', '', 5, 9351, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9661, 'Inconnu', 'Le poireau repousse la mouche de la carotte', 5, 9351, 9378);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9662, 'Inconnu', '', 5, 9351, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9663, 'Inconnu', '', 5, 9351, 9382);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9664, 'Inconnu', '', 5, 9351, 9556);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9665, 'Inconnu', '', 5, 9356, 9358);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9666, 'Inconnu', '', 5, 9356, 9359);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9667, 'Inconnu', 'La piéride du chou est repoussée par la tomate', 5, 9356, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9668, 'Inconnu', '', 5, 9356, 9382);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9669, 'Inconnu', 'La menthe protège les choux des papillons', 5, 9356, 9387);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9670, 'Inconnu', 'La sauge protège les choux des papillons', 5, 9356, 9386);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9671, 'Inconnu', '', 5, 9356, 9383);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9672, 'Inconnu', '', 5, 9356, 9374);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9673, 'Inconnu', '', 5, 9356, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9674, 'Inconnu', 'L''hysope empêche les mouches blanche de pondre dans les choux', 5, 9356, 9551);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9675, 'Inconnu', 'La piéride du chou est repoussée par le céleri', 5, 9356, 9552);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9676, 'Inconnu', '', 5, 9356, 9392);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9677, 'Inconnu', '', 5, 9356, 9375);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9678, 'Inconnu', 'La piéride du chou n''aime pas l''odeur de la tomate. L''effet protecteur est renforcé lorsqu''on met entre les plantes menacées, les gourmands des tomates.', 5, 9356, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9679, 'Inconnu', 'La piéride du chou n''aime pas l''odeur du céleri', 5, 9356, 9552);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9680, 'Inconnu', '', 5, 9364, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9681, 'Inconnu', '', 5, 9364, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9682, 'Inconnu', '', 5, 9364, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9683, 'Inconnu', '', 5, 9364, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9684, 'Inconnu', '', 5, 9364, 9385);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9685, 'Inconnu', '', 5, 9364, 9375);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9686, 'Inconnu', '', 5, 9364, 9393);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9687, 'Inconnu', '', 5, 9364, 9359);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9688, 'Inconnu', '', 5, 9364, 9370);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9689, 'Inconnu', '', 5, 9364, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9690, 'Inconnu', '', 5, 9362, 9363);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9691, 'Inconnu', '', 5, 9362, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9692, 'Inconnu', '', 5, 9362, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9693, 'Inconnu', '', 5, 9362, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9694, 'Inconnu', '', 5, 9362, 9370);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9695, 'Inconnu', '', 5, 9362, 9389);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9696, 'Inconnu', '', 5, 9362, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9697, 'Inconnu', '', 5, 9362, 9354);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9698, 'Inconnu', '', 5, 9362, 9388);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9699, 'Inconnu', '', 5, 9362, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9700, 'Inconnu', 'L’aneth protège les concombres', 5, 9362, 9352);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9701, 'Inconnu', '', 5, 9367, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9702, 'Inconnu', '', 5, 9367, 9366);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9703, 'Inconnu', 'Le doryphore de la pomme de terre est repoussé par le pois', 5, 9367, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9704, 'Inconnu', '', 5, 9367, 9371);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9705, 'Inconnu', '', 5, 9367, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9706, 'Inconnu', '', 5, 9367, 9375);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9707, 'Inconnu', '', 5, 9367, 9393);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9708, 'Inconnu', '', 5, 9367, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9709, 'Inconnu', '', 5, 9367, 9392);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9710, 'Inconnu', 'Le persil rend la tomate plus résistante aux maladies', 5, 9360, 9368);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9711, 'Inconnu', '', 5, 9360, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9712, 'Inconnu', '', 5, 9360, 9378);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9713, 'Inconnu', '', 5, 9360, 9375);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9714, 'Inconnu', '', 5, 9360, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9715, 'Inconnu', 'Le basilic rend la tomate plus résistante aux maladies', 5, 9360, 9363);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9716, 'Inconnu', '', 5, 9360, 9384);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9717, 'Inconnu', '', 5, 9360, 9393);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9718, 'Inconnu', '', 5, 9360, 9392);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9719, 'Inconnu', '', 5, 9360, 9374);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9720, 'Inconnu', '', 5, 9384, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9721, 'Inconnu', '', 5, 9384, 9368);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9722, 'Inconnu', '', 5, 9384, 9363);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9723, 'Inconnu', '', 5, 9384, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9724, 'Inconnu', '', 5, 9359, 9369);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9725, 'Inconnu', '', 5, 9359, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9726, 'Inconnu', '', 5, 9359, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9727, 'Inconnu', '', 5, 9359, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9728, 'Inconnu', '', 5, 9359, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9729, 'Inconnu', '', 5, 9359, 9390);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9730, 'Inconnu', '', 5, 9359, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9731, 'Inconnu', 'Le vers de framboisier est repoussé par la myosotis. Il empêche le vers de proliférer', 5, 9372, 9373);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9732, 'Inconnu', '', 5, 9385, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9733, 'Inconnu', '', 5, 9385, 9363);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9734, 'Inconnu', '', 5, 9371, 9374);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9735, 'Inconnu', '', 5, 9371, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9736, 'Inconnu', '', 5, 9371, 9391);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9737, 'Inconnu', '', 5, 9371, 9390);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9738, 'Inconnu', '', 5, 9371, 9370);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9739, 'Inconnu', '', 5, 9371, 9354);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9740, 'Inconnu', '', 5, 9371, 9392);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9741, 'Inconnu', 'La capucine éloigne les punaises des courgettes et citrouilles', 5, 9371, 9374);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9742, 'Inconnu', '', 5, 9390, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9743, 'Inconnu', '', 5, 9390, 9392);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9744, 'Inconnu', '', 5, 9390, 9391);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9745, 'Inconnu', '', 5, 9390, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9746, 'Inconnu', '', 5, 9361, 9390);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9747, 'Inconnu', '', 5, 9361, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9748, 'Inconnu', '', 5, 9361, 9354);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9749, 'Inconnu', '', 5, 9370, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9750, 'Inconnu', '', 5, 9370, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9751, 'Inconnu', '', 5, 9370, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9752, 'Inconnu', '', 5, 9370, 9371);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9753, 'Inconnu', '', 5, 9394, 9388);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9754, 'Inconnu', 'La mouche de l’oignon est repoussée par les carottes. Leur odeur repousse les mouches.', 5, 9377, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9755, 'Inconnu', '', 5, 9377, 9390);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9756, 'Inconnu', 'Les carottes contribues à la lutte contre la teigne du poireau', 5, 9378, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9757, 'Inconnu', '', 5, 9396, 9395);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9758, 'Inconnu', 'L''ail planté aux pieds des pêchers pour protéger de la cloque', 5, 9396, 9376);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9759, 'Inconnu', 'L''oignon planté aux pieds des pêchers pour protéger de la cloque', 5, 9396, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9760, 'Inconnu', '', 5, 9397, 9386);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9761, 'Inconnu', 'La ciboulette se plante près des pommiers pour prévenir de la tavelure, de la gale et des chancres', 5, 9398, 9379);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9762, 'Inconnu', 'Plantée au pied des pommiers, elle prévient contre le puceron lanigère', 5, 9398, 9374);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9763, 'Inconnu', '', 5, 9365, 9354);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9764, 'Inconnu', '', 5, 9365, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9765, 'Inconnu', '', 5, 9365, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9766, 'Inconnu', '', 5, 9365, 9370);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9767, 'Inconnu', '', 5, 9365, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9768, 'Inconnu', '', 5, 9354, 9391);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9769, 'Inconnu', '', 5, 9354, 9387);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9770, 'Inconnu', '', 5, 9354, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9771, 'Inconnu', '', 5, 9354, 9374);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9772, 'Inconnu', '', 5, 9354, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9773, 'Inconnu', '', 5, 9354, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9774, 'Inconnu', '', 5, 9354, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9775, 'Inconnu', 'Les géraniums protègent les rosiers', 5, 9381, 9400);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9776, 'Inconnu', 'L''ail planté au pied des rosiers les rends plus beaux et résistants', 5, 9381, 9376);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9777, 'Inconnu', 'Les pucerons noirs des rosiers sont repoussés par la menthe verte ou poivrée', 5, 9381, 9387);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9778, 'Inconnu', 'Le basilic s''associe parfaitement avec le genre capsicum', 5, 9554, 9363);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9779, 'Inconnu', '', 5, 9555, 9366);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9780, 'Inconnu', '', 5, 9359, 9354);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9781, 'Inconnu', '', 5, 9359, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9782, 'Inconnu', '', 5, 9359, 9355);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9783, 'Inconnu', '', 5, 9552, 9378);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9784, 'Inconnu', '', 5, 9552, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9785, 'Inconnu', 'Le céleri cultivé seul n''utilise qu''une partie des substances nutritives trouvées dans le sol. Quand on le plante avec du chou fleur, il les utilise mieux, de même que ce dernier. La récolte est alors meilleure pour les deux plantes.', 5, 9552, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9786, 'Inconnu', '', 5, 9552, 9391);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9787, 'Inconnu', '', 5, 9552, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9788, 'Inconnu', '', 5, 9552, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9789, 'Inconnu', 'Le chou fleur utilise mieux les nutriments présents dans le sols lorsqu''il accompagné du céleri, de même pour ce dernier.', -5, 9356, 9552);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9790, 'Inconnu', '', -5, 9376, 9366);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9791, 'Inconnu', '', -5, 9376, 9557);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9792, 'Inconnu', '', -5, 9376, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9793, 'Inconnu', '', -5, 9376, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9794, 'Inconnu', 'En compagnie d''aneth la carotte est sensible aux maladies et aux ravageurs et au mieux végètera. Elle ne poussent pas là où auparavant il y en avait déjà', -5, 9351, 9352);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9795, 'Inconnu', '', -5, 9561, 9558);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9796, 'Inconnu', '', -5, 9561, 9386);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9797, 'Inconnu', '', -5, 9561, 9559);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9798, 'Inconnu', '', -5, 9561, 9560);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9799, 'Inconnu', '', -5, 9555, 9366);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9800, 'Inconnu', '', -5, 9363, 9562);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9801, 'Inconnu', '', -5, 9359, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9802, 'Inconnu', '', -5, 9359, 9391);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9803, 'Inconnu', '', -5, 9354, 9564);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9804, 'Inconnu', '', -5, 9356, 9390);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9805, 'Inconnu', '', -5, 9356, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9806, 'Inconnu', '', -5, 9356, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9807, 'Inconnu', '', -5, 9362, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9808, 'Inconnu', '', -5, 9362, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9809, 'Inconnu', '', -5, 9362, 9371);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9810, 'Inconnu', '', -5, 9371, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9811, 'Inconnu', '', -5, 9377, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9812, 'Inconnu', '', -5, 9377, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9813, 'Inconnu', '', -5, 9377, 9366);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9814, 'Inconnu', '', -5, 9377, 9557);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9815, 'Inconnu', '', -5, 9391, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9816, 'Inconnu', '', -5, 9391, 9359);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9817, 'Inconnu', '', -5, 9560, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9818, 'Inconnu', '', -5, 9560, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9819, 'Inconnu', '', -5, 9560, 9558);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9820, 'Inconnu', '', -5, 9560, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9821, 'Inconnu', '', -5, 9560, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9822, 'Inconnu', '', -5, 9560, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9823, 'Inconnu', 'L''absinthe semble gêner la formation des graines', -5, 9560, 9561);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9824, 'Inconnu', 'La coriandre semble gêner la formation des graines', -5, 9560, 9369);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9825, 'Inconnu', '', -5, 9364, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9826, 'Inconnu', '', -5, 9364, 9376);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9827, 'Inconnu', '', -5, 9364, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9828, 'Inconnu', '', -5, 9364, 9560);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9829, 'Inconnu', '', -5, 9364, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9830, 'Inconnu', '', -5, 9361, 9389);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9831, 'Inconnu', '', -5, 9361, 9368);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9832, 'Inconnu', '', -5, 9394, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9833, 'Inconnu', '', -5, 9394, 9371);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9834, 'Inconnu', '', -5, 9378, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9835, 'Inconnu', '', -5, 9378, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9836, 'Inconnu', '', -5, 9378, 9366);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9837, 'Inconnu', '', -5, 9365, 9376);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9838, 'Inconnu', '', -5, 9365, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9839, 'Inconnu', '', -5, 9365, 9378);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9840, 'Inconnu', '', -5, 9365, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9841, 'Inconnu', '', -5, 9367, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9842, 'Inconnu', '', -5, 9367, 9371);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9843, 'Inconnu', '', -5, 9367, 9351);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9844, 'Inconnu', '', -5, 9367, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9845, 'Inconnu', '', -5, 9367, 9372);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9846, 'Inconnu', '', -5, 9367, 9565);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9847, 'Inconnu', '', -5, 9367, 9389);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9848, 'Inconnu', '', -5, 9367, 9394);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9849, 'Inconnu', '', -5, 9360, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9850, 'Inconnu', '', -5, 9360, 9362);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9851, 'Inconnu', '', -5, 9360, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9852, 'Inconnu', '', -5, 9360, 9367);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9853, 'Inconnu', '', -5, 9360, 9359);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9854, 'Inconnu', '', -5, 9360, 9365);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9855, 'Inconnu', '', -5, 9386, 9377);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9856, 'Inconnu', '', -5, 9368, 9361);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9857, 'Inconnu', '', -5, 9390, 9356);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9858, 'Inconnu', '', -5, 9384, 9360);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9859, 'Inconnu', '', -5, 9384, 9364);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9860, 'Inconnu', '', -5, 9384, 9368);
insert into public.allelopathie (id, type, description, impact, cible_id, origine_id) values (9861, 'Inconnu', '', -5, 9385, 9364);
