insert into public.nom_vernaculaire (id, nom, description) values (9301, 'carotte', null);
insert into public.nom_vernaculaire (id, nom, description) values (9302, 'carotte jaune du doubs', null);
insert into public.nom_vernaculaire (id, nom, description) values (9303, 'aneth', null);
insert into public.nom_vernaculaire (id, nom, description) values (9304, 'cresson', null);
insert into public.nom_vernaculaire (id, nom, description) values (9305, 'radis', null);
insert into public.nom_vernaculaire (id, nom, description) values (9306, 'radis 18 jours', null);
insert into public.nom_vernaculaire (id, nom, description) values (9307, 'radis kocto hf1', null);
insert into public.nom_vernaculaire (id, nom, description) values (9308, 'raifort', null);
insert into public.nom_vernaculaire (id, nom, description) values (9309, 'chou commun', null);
insert into public.nom_vernaculaire (id, nom, description) values (9310, 'chou rave', null);
insert into public.nom_vernaculaire (id, nom, description) values (9311, 'brocoli', null);
insert into public.nom_vernaculaire (id, nom, description) values (9312, 'chou fleur', null);
insert into public.nom_vernaculaire (id, nom, description) values (9313, 'chou cabus', null);
insert into public.nom_vernaculaire (id, nom, description) values (9314, 'chou cabus coeur de boeuf des vertus', null);
insert into public.nom_vernaculaire (id, nom, description) values (9315, 'chou fleur merveille de toutes saisons', null);
insert into public.nom_vernaculaire (id, nom, description) values (9316, 'navet rouge plat hâtif à feuille entière', null);
insert into public.nom_vernaculaire (id, nom, description) values (9317, 'chou de chine', null);
insert into public.nom_vernaculaire (id, nom, description) values (9318, 'roquette', null);
insert into public.nom_vernaculaire (id, nom, description) values (9319, 'roquette cultivée', null);
insert into public.nom_vernaculaire (id, nom, description) values (9320, 'roquette sauvage', null);
insert into public.nom_vernaculaire (id, nom, description) values (9321, 'sarriette', null);
insert into public.nom_vernaculaire (id, nom, description) values (9322, 'sarriette commune', null);
insert into public.nom_vernaculaire (id, nom, description) values (9323, 'betterave', null);
insert into public.nom_vernaculaire (id, nom, description) values (9324, 'bette', null);
insert into public.nom_vernaculaire (id, nom, description) values (9325, 'betterave de détroit améliorée 3', null);
insert into public.nom_vernaculaire (id, nom, description) values (9326, 'tomate', null);
insert into public.nom_vernaculaire (id, nom, description) values (9327, 'tomate noire russe', null);
insert into public.nom_vernaculaire (id, nom, description) values (9328, 'tomate beefsteak', null);
insert into public.nom_vernaculaire (id, nom, description) values (9329, 'laitue', null);
insert into public.nom_vernaculaire (id, nom, description) values (9330, 'laitue rouge grenobloise', null);
insert into public.nom_vernaculaire (id, nom, description) values (9331, 'laitue reine de mai de pleine terre', null);
insert into public.nom_vernaculaire (id, nom, description) values (9332, 'laitue batavia lollo rossa', null);
insert into public.nom_vernaculaire (id, nom, description) values (9333, 'laitue pommée grosse blonde paresseuse', null);
insert into public.nom_vernaculaire (id, nom, description) values (9334, 'laitue pommée reine de mai', null);
insert into public.nom_vernaculaire (id, nom, description) values (9335, 'laitue batavia iceberg reine des glaces', null);
insert into public.nom_vernaculaire (id, nom, description) values (9336, 'laitue cressonnette marocaine', null);
insert into public.nom_vernaculaire (id, nom, description) values (9337, 'laitue à couper', null);
insert into public.nom_vernaculaire (id, nom, description) values (9338, 'concombre', null);
insert into public.nom_vernaculaire (id, nom, description) values (9339, 'concombre vert long maraîcher', null);
insert into public.nom_vernaculaire (id, nom, description) values (9340, 'basilic', null);
insert into public.nom_vernaculaire (id, nom, description) values (9341, 'haricot', null);
insert into public.nom_vernaculaire (id, nom, description) values (9342, 'pois', null);
insert into public.nom_vernaculaire (id, nom, description) values (9343, 'pois nain norli grain rond', null);
insert into public.nom_vernaculaire (id, nom, description) values (9344, 'fève', null);
insert into public.nom_vernaculaire (id, nom, description) values (9345, 'fève aguadulce à très longue cosse', null);
insert into public.nom_vernaculaire (id, nom, description) values (9346, 'pomme de terre', null);
insert into public.nom_vernaculaire (id, nom, description) values (9347, 'persil', null);
insert into public.nom_vernaculaire (id, nom, description) values (9348, 'persil frisé vert foncé ou double', null);
insert into public.nom_vernaculaire (id, nom, description) values (9349, 'coriandre', null);
insert into public.nom_vernaculaire (id, nom, description) values (9350, 'maïs', null);
insert into public.nom_vernaculaire (id, nom, description) values (9401, 'maïs doux bantam', null);
insert into public.nom_vernaculaire (id, nom, description) values (9402, 'courge', null);
insert into public.nom_vernaculaire (id, nom, description) values (9403, 'courge pâtisson blanc', null);
insert into public.nom_vernaculaire (id, nom, description) values (9404, 'potiron', null);
insert into public.nom_vernaculaire (id, nom, description) values (9405, 'potiron petit bonnet turc', null);
insert into public.nom_vernaculaire (id, nom, description) values (9406, 'courgette', null);
insert into public.nom_vernaculaire (id, nom, description) values (9407, 'framboisier', null);
insert into public.nom_vernaculaire (id, nom, description) values (9408, 'myosotis des champs', null);
insert into public.nom_vernaculaire (id, nom, description) values (9409, 'grande capucine', null);
insert into public.nom_vernaculaire (id, nom, description) values (9410, 'oeillet d''inde', null);
insert into public.nom_vernaculaire (id, nom, description) values (9411, 'ail', null);
insert into public.nom_vernaculaire (id, nom, description) values (9412, 'échalote', null);
insert into public.nom_vernaculaire (id, nom, description) values (9413, 'oignon', null);
insert into public.nom_vernaculaire (id, nom, description) values (9414, 'poireau', null);
insert into public.nom_vernaculaire (id, nom, description) values (9415, 'poireau monstrueux de carentan', null);
insert into public.nom_vernaculaire (id, nom, description) values (9416, 'ciboulette', null);
insert into public.nom_vernaculaire (id, nom, description) values (9417, 'ciboulette commune', null);
insert into public.nom_vernaculaire (id, nom, description) values (9418, 'civette', null);
insert into public.nom_vernaculaire (id, nom, description) values (9419, 'ciboule de chine', null);
insert into public.nom_vernaculaire (id, nom, description) values (9420, 'rosier de france', null);
insert into public.nom_vernaculaire (id, nom, description) values (9421, 'romarin', null);
insert into public.nom_vernaculaire (id, nom, description) values (9422, 'thym commun', null);
insert into public.nom_vernaculaire (id, nom, description) values (9423, 'thym ordinaire', null);
insert into public.nom_vernaculaire (id, nom, description) values (9424, 'asperge', null);
insert into public.nom_vernaculaire (id, nom, description) values (9425, 'aubergine', null);
insert into public.nom_vernaculaire (id, nom, description) values (9426, 'aubergine violetta di firenze', null);
insert into public.nom_vernaculaire (id, nom, description) values (9427, 'sauge', null);
insert into public.nom_vernaculaire (id, nom, description) values (9428, 'sauge officinale', null);
insert into public.nom_vernaculaire (id, nom, description) values (9429, 'menthe poivrée', null);
insert into public.nom_vernaculaire (id, nom, description) values (9430, 'origan', null);
insert into public.nom_vernaculaire (id, nom, description) values (9431, 'origan marjolaine', null);
insert into public.nom_vernaculaire (id, nom, description) values (9432, 'marjolaine vivace', null);
insert into public.nom_vernaculaire (id, nom, description) values (9433, 'tournesol', null);
insert into public.nom_vernaculaire (id, nom, description) values (9434, 'fraisier des bois', null);
insert into public.nom_vernaculaire (id, nom, description) values (9435, 'épinard', null);
insert into public.nom_vernaculaire (id, nom, description) values (9436, 'épinard d''été matador', null);
insert into public.nom_vernaculaire (id, nom, description) values (9437, 'épinard géant d''hiver', null);
insert into public.nom_vernaculaire (id, nom, description) values (9438, 'bourrache', null);
insert into public.nom_vernaculaire (id, nom, description) values (9439, 'souci officinal', null);
insert into public.nom_vernaculaire (id, nom, description) values (9440, 'melon', null);
insert into public.nom_vernaculaire (id, nom, description) values (9441, 'melon ancien vieille france', null);
insert into public.nom_vernaculaire (id, nom, description) values (9442, 'tanaisie', null);
insert into public.nom_vernaculaire (id, nom, description) values (9443, 'pêcher', null);
insert into public.nom_vernaculaire (id, nom, description) values (9444, 'poirier', null);
insert into public.nom_vernaculaire (id, nom, description) values (9445, 'pommier', null);
insert into public.nom_vernaculaire (id, nom, description) values (9446, 'bouleau', null);
insert into public.nom_vernaculaire (id, nom, description) values (9447, 'géranium des prés', null);
insert into public.nom_vernaculaire (id, nom, description) values (9448, 'hysope', null);
insert into public.nom_vernaculaire (id, nom, description) values (9449, 'céleri', null);
insert into public.nom_vernaculaire (id, nom, description) values (9450, 'cataire', null);
insert into public.nom_vernaculaire (id, nom, description) values (9601, 'poivron', null);
insert into public.nom_vernaculaire (id, nom, description) values (9602, 'piment', null);
insert into public.nom_vernaculaire (id, nom, description) values (9603, 'piment fort de cayenne', null);
insert into public.nom_vernaculaire (id, nom, description) values (9604, 'artichaut', null);
insert into public.nom_vernaculaire (id, nom, description) values (9605, 'artichaut gros vert de laon', null);
insert into public.nom_vernaculaire (id, nom, description) values (9606, 'scorsonère des prés', null);
insert into public.nom_vernaculaire (id, nom, description) values (9607, 'lentille', null);
insert into public.nom_vernaculaire (id, nom, description) values (9608, 'carvi', null);
insert into public.nom_vernaculaire (id, nom, description) values (9609, 'anis vert', null);
insert into public.nom_vernaculaire (id, nom, description) values (9610, 'fenouil', null);
insert into public.nom_vernaculaire (id, nom, description) values (9611, 'absinthe', null);
insert into public.nom_vernaculaire (id, nom, description) values (9612, 'rue officinale', null);
insert into public.nom_vernaculaire (id, nom, description) values (9613, 'noyer', null);
insert into public.nom_vernaculaire (id, nom, description) values (9614, 'cerfeuil', null);
insert into public.nom_vernaculaire (id, nom, description) values (9615, 'arroche des jardins', null);
insert into public.nom_vernaculaire (id, nom, description) values (9616, 'pourpier', null);
insert into public.nom_vernaculaire (id, nom, description) values (9617, 'mâche', null);
insert into public.nom_vernaculaire (id, nom, description) values (9618, 'mâche à grosse graine', null);
